package kea.botxo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * The "main" class that starts the program - auto generated by Spring Boot/Initializer.
 */
@SpringBootApplication
public class BotxoApplication {
	public static void main(String[] args) {
		SpringApplication.run(BotxoApplication.class, args);
	}
}
