package kea.botxo.testserver;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * The "main" class that starts the program - auto generated by Spring Boot/Initializer.
 */
@SpringBootApplication
public class TestserverApplication {

	public static void main(String[] args) {
		SpringApplication.run(TestserverApplication.class, args);
	}

}
